### ISSUE TITLE
Error exclusiveMaximum should be number on validating schema

### ISSUE THREAD

**Issue by snakuzzo** [anttiviljami/openapi-backend#115]
I'm trying to create a mockserver. On some specs I have this...

```
{
  "name": "myparameter",
  "in": "path",
  "description": "my parameter",
  "required": true,
  "schema": {
    "type": "number",
    "minimum": 1,
    "maximum": 20,
    "exclusiveMinimum": false,
    "exclusiveMaximum": true
  }
}
```

but when I validate schema raise this error...

```
(node:38680) UnhandledPromiseRejectionWarning: Error: schema is invalid: data.properties['path'].properties['numLinea'].exclusiveMaximum should be number
    at Ajv.validateSchema (/home/snakuzzo/workspace/mockserver/node_modules/ajv/lib/ajv.js:178:16)
    at Ajv._addSchema (/home/snakuzzo/workspace/mockserver/node_modules/ajv/lib/ajv.js:307:10)
    at Ajv.compile (/home/snakuzzo/workspace/mockserver/node_modules/ajv/lib/ajv.js:113:24)
    at OpenAPIValidator.buildRequestValidatorsForOperation (/home/snakuzzo/workspace/mockserver/node_modules/openapi-backend/validation.js:408:41)
    at Array.map (<anonymous>)
    at new OpenAPIValidator (/home/snakuzzo/workspace/mockserver/node_modules/openapi-backend/validation.js:85:20)
    at OpenAPIBackend.init (/home/snakuzzo/workspace/mockserver/node_modules/openapi-backend/backend.js:116:30)
```

**Comment by anttiviljami** [comment]
HI @snakuzzo ! 

Looks like your definition file is using an outdated version of JSON Schema. See the spec here for `exclusiveMinimum` / `exclusiveMaximum` https://json-schema.org/understanding-json-schema/reference/numeric.html

You may be able to configure ajv to use an older version of the JSON schema using [`opts.customizeAjv` ](https://github.com/anttiviljami/openapi-backend/blob/master/DOCS.md#parameter-optscustomizeajvoriginalajv-ajvopts-validationcontext) if necessary, but I would warmly recommend keeping your definition files up to date with the latest OAS / JSON Schema specification

**Comment by snakuzzo** [comment]
Hi @anttiviljami and thanks! ;)

Sadly definitions are not mine :(
I'm trying to add old schema as mentioned here https://ajv.js.org/#api under **Using version 6**.
Here is my code...

```
  let api = new OpenAPIBackend({
    definition: definitionPath,
    strict: true,
    quick: false,
    validate: true,
    ajvOpts: { schemaId: 'auto' },
    customizeAjv: () => new Ajv().addMetaSchema(require('ajv/lib/refs/json-schema-draft-04.json')),
    handlers: {
      validationFail: (c, req, res, next) => res.status(400).json({ err: c.validation.errors }),
      notFound: (c, req, res, next) => next(),
      notImplemented: (c, req, res, next) => {
        const { status, mock } = c.api.mockResponseForOperation(c.operation.operationId);
        return res.status(status).json(mock);
      },
    },
  });
```

... but I have this error...

```
schema id ignored http://json-schema.org/draft-04/schema#
schema id ignored http://json-schema.org/draft-04/schema#
(node:41051) UnhandledPromiseRejectionWarning: Error: no schema with key or ref "http://json-schema.org/draft-04/schema#"
    at Ajv.validate (/home/snakuzzo/workspace/mockserver/node_modules/ajv/lib/ajv.js:93:19)
    at Ajv.validateSchema (/home/snakuzzo/workspace/mockserver/node_modules/ajv/lib/ajv.js:174:20)
    at Ajv._addSchema (/home/snakuzzo/workspace/mockserver/node_modules/ajv/lib/ajv.js:307:10)
    at Ajv.addSchema (/home/snakuzzo/workspace/mockserver/node_modules/ajv/lib/ajv.js:137:29)
    at Ajv.addMetaSchema (/home/snakuzzo/workspace/mockserver/node_modules/ajv/lib/ajv.js:152:8)
    at OpenAPIValidator.customizeAjv (/home/snakuzzo/workspace/mockserver/app.js:44:35)
    at OpenAPIValidator.getAjv (/home/snakuzzo/workspace/mockserver/node_modules/openapi-backend/validation.js:314:25)
    at OpenAPIValidator.buildRequestValidatorsForOperation (/home/snakuzzo/workspace/mockserver/node_modules/openapi-backend/validation.js:351:51)
    at Array.map (<anonymous>)
    at new OpenAPIValidator (/home/snakuzzo/workspace/mockserver/node_modules/openapi-backend/validation.js:85:20)
```

am I doing something wrong ?
Can you help me to solve this problem?

Thanks

**Comment by anttiviljami** [comment]
Sorry @snakuzzo. I've never tried to run Ajv with older versions of JSON Schema :/ I'd seek advice from the Ajv project.

**Comment by YuefengLi** [comment]
I ran into similar cases where openapi-backend keeps saying `exclusiveMinimum` must be a number. I'm using OAS 3.0.1 and i found [all OAS 3.0.x](https://spec.openapis.org/oas/v3.0.3#schema-object) is using an old version of JSON schema which is [draft5](https://json-schema.org/specification-links.html#draft-6). 
Still exploring the solution...
