### ISSUE TITLE
[Question] Can we use both handlers definition in OpenAPIBackend and api.register?

### ISSUE THREAD

**Issue by Codermar** [anttiviljami/openapi-backend#30]
I've been playing with openapi-backend for a little bit and I am still trying to understand how it works.
I should be able to combine handlers definitions in OpenAPIBackend and api.register right? Because I tried and I get:

```api listening at http://localhost:9091
(node:39783) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/usr/local/2019/openapi-backend-examples/express-resp-validation/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/usr/local/2019/openapi-backend-examples/express-resp-validation/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/usr/local/2019/openapi-backend-examples/express-resp-validation/node_modules/express/lib/response.js:267:15)
    at postResponseHandler (/usr/local/2019/openapi-backend-examples/express-resp-validation/index.js:61:30)
    at OpenAPIBackend.<anonymous> (/usr/local/2019/openapi-backend-examples/express-resp-validation/node_modules/openapi-backend/backend.js:247:90)
    at step (/usr/local/2019/openapi-backend-examples/express-resp-validation/node_modules/openapi-backend/backend.js:43:23)
    at Object.next (/usr/local/2019/openapi-backend-examples/express-resp-validation/node_modules/openapi-backend/backend.js:24:53)
    at fulfilled (/usr/local/2019/openapi-backend-examples/express-resp-validation/node_modules/openapi-backend/backend.js:15:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:39783) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:39783) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code..```

This does not happen if I have the operationId handler inside api.register()

So a couple of questions:
Does the  postResponseHandler applies to all of the endpoints like notFound or validationFail?
Does that error sound like a possible bug?

Thanks

Awesome package BTW! 👍

**Comment by anttiviljami** [comment]
> I should be able to combine handlers definitions in OpenAPIBackend and api.register right

You mean you want to register handlers in both `OpenAPIBackend()` constructor and `api.register()`? Yes that should work just fine as long as you call `api.init()` after.

The error you've pasted is generally because something in your handler code already starts outputting something to the express response, which causes it to send response headers. After that, you can't call `res.send()` or `res.json()`or `res.header()` or `res.status()` again.

> Does the  postResponseHandler applies to all of the endpoints like notFound or validationFail?

Yes. postResponseHandler applies even to notFound and validationFail handlers.

> Does that error sound like a possible bug?

I don't think so. Could you post some example code that you feel like is a bug?

> Awesome package BTW! 👍 

Thanks! 🙌

**Comment by anttiviljami** [comment]
Closing this issue since it's been a couple of weeks. Feel free to comment if you still need help with this @Codermar !

**Comment by iursinoliveperson** [comment]
I had that issue. is "return res.status(200).json({stuff: "thing"})" not something we are allowed to do in our other handlers? If so then what do we do instead?

**Comment by iursinoliveperson** [comment]
```
webapp_1  | (node:1) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
webapp_1  |     at ServerResponse.setHeader (_http_outgoing.js:485:11)
webapp_1  |     at ServerResponse.header (/app/node_modules/express/lib/response.js:771:10)
webapp_1  |     at ServerResponse.send (/app/node_modules/express/lib/response.js:170:12)
webapp_1  |     at ServerResponse.json (/app/node_modules/express/lib/response.js:267:15)
webapp_1  |     at /app/src/Server.js:36:32
webapp_1  |     at OpenAPIBackend.handleRequest (/app/node_modules/openapi-backend/backend.js:177:39)
webapp_1  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
webapp_1  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
(rejection id: 1)
webapp_1  | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

Handler looks like this:
```
handlers: {
        postDevAccount: convertBodyHandlerToHandler(postDevAccount),
        validationFail: (c, req, res) => {
            return res.status(400).json({status: 400, err: c?.validation?.errors})
        },
        postResponseHandler: (c, req, res) => {
            if (!c) {
                throw Error("It shouldn't be possible not to have a context.")
            }
            if (!c.operation) {
                throw Error("postResponseHandler should have an operation in the context.")
            }
            const valid = c.api.validateResponse(c?.response, c.operation)
            if (valid.errors) {
                return res.status(500).json({ status: 500, err: valid.errors })
            }
            return res.status(200).json(c.response)
        }
    }
```

and convertBodyHandlerToHandler is:

```
export function convertBodyHandlerToHandler<B, RES>(handler: BodyHandler<B, RES>): Handler {
    return async (ct, req: ParsedRequest, res: Response) => {
        return res.status(200).json(handler(req.body as B) as RES)
    }
}

export type BodyHandler<B, RES> = (request: B) => RES
```

And then the BodyHandler instance is:

```
export const postDevAccount: BodyHandler<DevAccountRequest, DevAccountResponse> = (requestBody: DevAccountRequest) => {
    console.log(requestBody)
    return {
        accountId: "stuff",
        zone: requestBody.region
    } as DevAccountResponse
}
```
