### ISSUE TITLE
Cannot open YAML file

### ISSUE THREAD

**Issue by tamon-persol** [anttiviljami/openapi-backend#431]
I m trying to combine MSW and openapi-backend but it seem that when i try to read a yaml file it doesn't work.

error

 ```
 console.warn
    {
      stack: 'ResolverError: Error opening file "/Users/suzukitamon/Documents/miraiz/api/specification.yaml"\n' +
        '    at ReadFileContext.callback (/Users/suzukitamon/Documents/miraiz/miraiz-sheet-frontend/node_modules/@apidevtools/json-schema-ref-parser/lib/resolvers/file.js:52:20)\n' +
        '    at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:314:13)',
      code: 'ERESOLVER',
      message: 'Error opening file "/Users/suzukitamon/Documents/miraiz/api/specification.yaml"',
      source: '/Users/suzukitamon/Documents/miraiz/api/specification.yaml',
      path: null,
      toJSON: [Function: toJSON],
      ioErrorCode: 'ENOENT',
      name: 'ResolverError',
      footprint: 'null+/Users/suzukitamon/Documents/miraiz/api/specification.yaml+ERESOLVER+Error opening file "/Users/suzukitamon/Documents/miraiz/api/specification.yaml"',
      toString: [Function: toString]
    }

      at OpenAPIBackend.init (node_modules/openapi-backend/src/backend.ts:203:17)
      at OpenAPIBackend.handleRequest (node_modules/openapi-backend/src/backend.ts:268:7)
      at node_modules/msw/src/handlers/RequestHandler.ts:232:49
      at RestHandler.run (node_modules/msw/src/handlers/RequestHandler.ts:215:28)
      at node_modules/msw/src/utils/getResponse.ts:50:20
      at getResponse (node_modules/msw/src/utils/getResponse.ts:41:18)
      at Object.<anonymous>.exports.until (node_modules/@open-draft/until/lib/until.js:10:22)
```  

code
```
import { rest } from 'msw';
import { OpenAPIBackend, ParsedRequest } from 'openapi-backend';

const api = new OpenAPIBackend({
  definition: '../api/specification.yaml'
});

export const handlers = [
  rest.get(`/*`, (req, res, ctx) => {
    const requestParser = {
      ...req,
      path: req.url.pathname,
      headers: req.headers.all(),
      method: req.method
    };
    return api.handleRequest(requestParser, res, ctx);
  })
];

```

**Comment by joeythomaschaske** [comment]
What was the fix?

**Comment by joeythomaschaske** [comment]
> What was the fix?

Lol started a new project and I'm back again
