### ISSUE TITLE
OpenAPI 3.1 Support

### ISSUE THREAD

**Issue by revnode** [anttiviljami/openapi-backend#532]
It looks like OpenAPI 3.1 support was added a few years back? I'm having trouble with it.

When executing:

```
const definition = `{
  "openapi": "3.1.0",
  "info": {
    "version": "1.0.0",
    "title": "test",
    "description": "test",
    "contact": {
      "email": "test@test.com"
    },
    "license": {
      "name": "UNLICENSED",
      "url": "https://test.com/terms-conditions/"
    }
  },
  "servers": [
    {
      "url": "/api/v1"
    }
  ],
  "paths": {
    "/ping": {
      "get": {
        "operationId": "ping.get",
        "summary": "Checks if the API is operational.",
        "description": "Verifies the API is deployed and functioning properly.",
        "tags": [
          "Utilities"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "description": "The response to a ping should be pong.",
                      "type": "string",
                      "example": "pong"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "key": {
        "type": "apiKey",
        "in": "header",
        "name": "key",
        "description": "test"
      },
      "session": {
        "type": "apiKey",
        "in": "header",
        "name": "session",
        "description": "test"
      }
    },
    "schemas": {
      "test": {
        "type": "object",
        "properties": {
          "test": {
            "description": "This is a test.",
            "type": [
              "string",
              "null"
            ]
          }
        }
      }
    }
  }
}`;
const api = new OpenAPIBackend({
  definition,
  apiRoot: "/api/v1"
});
```

I get errors like:

```
{
  "instancePath": "/components/schemas/test/properties/test/type",
  "schemaPath": "#/properties/type/type",
  "keyword": "type",
  "params": {
    "type": "string"
  },
  "message": "must be string"
}
```

If I set the type to a string, the error goes away. But it should support an array? Any help appreciated. Thanks!

**Comment by revnode** [comment]
It looks like the culprit might be https://www.npmjs.com/package/openapi-schema-validator which is used internally? It doesn't look like `openapi-schema-validator` supports 3.1

**Comment by revnode** [comment]
Seems there is a ticket for it: https://github.com/kogosoftwarellc/open-api/issues/837

For those running into the same issue, a quick hack is to set `quick` to `true` as an option to OpenAPIBackend to suppress the errors.

**Comment by Patrick-at-CELAD** [comment]
The schema validation is obviously done against OpenAPI 3.0 specs, not 3.1.
Example : const is allowed with 3.1 in "type: object" schema :

```
openapi: 3.1.0

info:
  title: test
  version: 1.0.0

paths: {}

components:
  schemas:
    Test:
      type: object
      properties:
        $type:
          type: string
          const: app.bsky.test
```

Should not get these errors :

```
Error: Document is not valid OpenAPI. 9 validation errors:
[
  {
    "instancePath": "/components/schemas/Test/properties/$type",
    "schemaPath": "#/additionalProperties",
    "keyword": "additionalProperties",
    "params": {
      "additionalProperty": "const"
    },
    "message": "must NOT have additional properties"
  },
  {
    "instancePath": "/components/schemas/Test/properties/$type",
    "schemaPath": "#/required",
    "keyword": "required",
    "params": {
      "missingProperty": "$ref"
    },
    "message": "must have required property '$ref'"
  },
  {
    "instancePath": "/components/schemas/Test/properties/$type",
    "schemaPath": "#/additionalProperties",
    "keyword": "additionalProperties",
    "params": {
      "additionalProperty": "type"
    },
    "message": "must NOT have additional properties"
  },
  {
    "instancePath": "/components/schemas/Test/properties/$type",
    "schemaPath": "#/additionalProperties",
    "keyword": "additionalProperties",
    "params": {
      "additionalProperty": "const"
    },
    "message": "must NOT have additional properties"
  },
  {
    "instancePath": "/components/schemas/Test/properties/$type",
    "schemaPath": "#/oneOf",
    "keyword": "oneOf",
    "params": {
      "passingSchemas": null
    },
    "message": "must match exactly one schema in oneOf"
  },
  {
    "instancePath": "/components/schemas/Test",
    "schemaPath": "#/required",
    "keyword": "required",
    "params": {
      "missingProperty": "$ref"
    },
    "message": "must have required property '$ref'"
  },
  {
    "instancePath": "/components/schemas/Test",
    "schemaPath": "#/additionalProperties",
    "keyword": "additionalProperties",
    "params": {
      "additionalProperty": "type"
    },
    "message": "must NOT have additional properties"
  },
  {
    "instancePath": "/components/schemas/Test",
    "schemaPath": "#/additionalProperties",
    "keyword": "additionalProperties",
    "params": {
      "additionalProperty": "properties"
    },
    "message": "must NOT have additional properties"
  },
  {
    "instancePath": "/components/schemas/Test",
    "schemaPath": "#/oneOf",
    "keyword": "oneOf",
    "params": {
      "passingSchemas": null
    },
    "message": "must match exactly one schema in oneOf"
  }
]
    at OpenAPIBackend.validateDefinition (/app/node_modules/openapi-backend/src/backend.ts:711:13)
    at OpenAPIBackend.init (/app/node_modules/openapi-backend/src/backend.ts:226:14) {stack: 'Error: Document is not valid OpenAPI. 9 valid…odules/openapi-backend/src/backend.ts:226:14)', message: 'Document is not valid OpenAPI. 9 validation …ust match exactly one schema in oneOf"
  }
]'}
```
